# Generated by Django 5.2 on 2025-04-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(choices=[('ARG', 'Argentina'), ('BR', 'Brasil'), ('URU', 'Uruguay'), ('USA', 'Estados Unidos'), ('MX', 'Mexico'), ('FRA', 'Francia'), ('ALE', 'Alemania'), ('ESP', 'España'), ('ING', 'Inglaterra')])),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
